# Generated by Django 4.0.7 on 2022-09-29 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletterApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.CharField(default=2, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post'),
        ),
    ]
