# Generated by Django 4.0.7 on 2022-09-29 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletterApp', '0002_comment_name_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(default='Sin Nombre', max_length=150),
        ),
    ]
