# Generated by Django 4.0.7 on 2022-10-04 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletterApp', '0004_post_is_important'),
    ]

    operations = [
        migrations.CreateModel(
            name='events_calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Sin Nombre', max_length=150)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
            ],
        ),
    ]
