# Generated by Django 4.0.7 on 2022-09-16 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativeApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tlb_member_phone',
            fields=[
                ('id_contact', models.AutoField(primary_key=True, serialize=False)),
                ('phone1', models.CharField(blank=True, db_column='Phone1', max_length=50, null=True)),
                ('type_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('status_fone', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tlb_member_phone',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='tlb_member_contact',
        ),
    ]
