# Generated by Django 4.0.7 on 2022-09-18 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrativeApp', '0002_tlb_member_phone_delete_tlb_member_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tlbmemberjob',
            options={'managed': False, 'ordering': ['id_member']},
        ),
    ]
